import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ro' | 'en' | 'de' | 'es' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  detectedFromLocation: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'header.search': 'Search for items...',
    'header.sell': 'Sell',
    'header.login': 'Log In',
    'header.signup': 'Sign Up',
    'header.dashboard': 'My Dashboard',
    'header.listings': 'My Listings',
    'header.favorites': 'Favorites',
    'header.messages': 'Messages',
    'header.orders': 'My Orders',
    'header.settings': 'Settings',
    'header.signout': 'Sign Out',
    'header.sellItem': 'Sell an Item',
    
    // Search
    'search.title': 'Search Products',
    'search.placeholder': 'What are you looking for?',
    'search.or': 'or search by image',
    'search.imageSearchDesc': 'Take a photo or upload an image to find similar products',
    'search.takePhoto': 'Take Photo',
    'search.uploadImage': 'Upload Image',
    'search.searchByImage': 'Search by Image',
    'search.analyzing': 'Analyzing...',
    'search.analyzingImage': 'Analyzing image...',
    'search.invalidImage': 'Please select a valid image file',
    
    // Home
    'home.hero.tagline': 'Buy & Sell Smart',
    'home.hero.subtitle': 'Join millions of people discovering great deals on unique items. From electronics to fashion, find what you\'re looking for.',
    'home.hero.searchPlaceholder': 'What are you looking for?',
    'home.hero.popular': 'Popular',
    'home.hero.furniture': 'Furniture',
    'home.hero.title': 'Buy & Sell Locally',
    'home.hero.cta': 'Start Browsing',
    'home.categories': 'Categories',
    'home.featured': 'Featured Listings',
    'home.viewAll': 'View All',
    'home.howItWorks': 'How It Works',
    'home.step1.title': 'List Your Item',
    'home.step1.desc': 'Take photos and create your listing in minutes',
    'home.step2.title': 'Connect with Buyers',
    'home.step2.desc': 'Chat directly with interested buyers',
    'home.step3.title': 'Get Paid Securely',
    'home.step3.desc': 'Receive payment through our secure platform',
    
    // Browse
    'browse.search': 'Search items...',
    'browse.filters': 'Filters',
    'browse.category': 'Category',
    'browse.allCategories': 'All Categories',
    'browse.priceRange': 'Price Range',
    'browse.condition': 'Condition',
    'browse.anyCondition': 'Any Condition',
    'browse.clearFilters': 'Clear Filters',
    'browse.sort': 'Sort by',
    'browse.newest': 'Newest First',
    'browse.priceLow': 'Price: Low to High',
    'browse.priceHigh': 'Price: High to Low',
    'browse.itemsFound': 'items found',
    'browse.noListings': 'No listings found matching your criteria',
    
    // Conditions
    'condition.new': 'New',
    'condition.like_new': 'Like New',
    'condition.good': 'Good',
    'condition.fair': 'Fair',
    'condition.poor': 'Poor',
    
    // Dashboard
    'dashboard.welcome': 'Welcome!',
    'dashboard.seller': 'Seller',
    'dashboard.newListing': 'New Listing',
    'dashboard.becomeSeller': 'Become a Seller',
    'dashboard.subscription': 'Platform Fee',
    'dashboard.subscribed': 'Active',
    'dashboard.subscribe': '8% commission on each sale',
    'dashboard.manageSubscription': 'View Fees',
    'dashboard.subscribeNow': 'Start Selling Free',
    'dashboard.sellerBenefits': 'Seller benefits: List products for free, 8% commission only when you sell. No monthly fees!',
    'dashboard.activeListings': 'Active Listings',
    'dashboard.totalViews': 'Total Views',
    'dashboard.totalEarned': 'Total Earned',
    'dashboard.myFavorites': 'My Favorites',
    'dashboard.itemsSaved': 'Items you\'ve saved',
    'dashboard.chatWithUsers': 'Chat with buyers & sellers',
    'dashboard.manageAccount': 'Manage your account',
    'dashboard.myListings': 'My Listings',
    'dashboard.noListings': 'No listings yet',
    'dashboard.startSelling': 'Start selling by creating your first listing',
    'dashboard.subscribeToSell': 'Activate monthly access to become a seller and create listings',
    'dashboard.createListing': 'Create Listing',
    'dashboard.loading': 'Loading...',
    'dashboard.subscriptionActivated': 'Access activated!',
    'dashboard.canCreateListings': 'You can now create listings.',
    'dashboard.subscriptionCanceled': 'Access payment canceled',
    'dashboard.canSubscribeAnytime': 'You can activate anytime.',
    
    // Settings tabs
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.payments': 'Payments',
    'settings.payouts': 'Payouts',
    'settings.shipping': 'Shipping',
    'settings.seller': 'Seller',
    'settings.notifications': 'Alerts',
    'settings.security': 'Security',
    
    // Profile settings
    'settings.profileInfo': 'Profile Information',
    'settings.profileDesc': 'Update your personal information visible to other users',
    'settings.changeAvatar': 'Change Avatar',
    'settings.displayName': 'Display Name',
    'settings.username': 'Username',
    'settings.email': 'Email',
    'settings.emailCantChange': 'Email cannot be changed',
    'settings.bio': 'Bio',
    'settings.bioPlaceholder': 'Tell others about yourself...',
    'settings.location': 'Location',
    'settings.phone': 'Phone',
    'settings.saveChanges': 'Save Changes',
    'settings.saving': 'Saving...',
    
    // Auth
    'auth.login': 'Log In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.loginButton': 'Log In',
    'auth.signupButton': 'Create Account',
    
    // Listing
    'listing.buyNow': 'Buy Now',
    'listing.addToCart': 'Add to Cart',
    'listing.contactSeller': 'Contact Seller',
    'listing.description': 'Description',
    'listing.sellerInfo': 'Seller Information',
    'listing.memberSince': 'Member since',
    'listing.viewProfile': 'View Profile',
    'listing.report': 'Report Listing',
    'listing.share': 'Share',
    'listing.placeBid': 'Place Bid',
    'listing.currentBid': 'Current Bid',
    'listing.startingBid': 'Starting Bid',
    'listing.auctionEnds': 'Auction Ends',
    'listing.inStock': 'In Stock',
    'listing.outOfStock': 'Out of Stock',
    'listing.freeShipping': 'Free Shipping',
    'listing.shipping': 'Shipping',
    'listing.location': 'Location',
    'listing.condition': 'Condition',
    'listing.sold': 'Sold',
    'listing.promoted': 'Promoted',
    
    // Orders
    'orders.myPurchases': 'My Purchases',
    'orders.myReturns': 'My Returns',
    'orders.pending': 'Pending',
    'orders.paid': 'Paid',
    'orders.shipped': 'Shipped',
    'orders.delivered': 'Delivered',
    'orders.cancelled': 'Cancelled',
    'orders.refunded': 'Refunded',
    'orders.awb': 'Tracking Number',
    'orders.addTracking': 'Add Tracking',
    'orders.confirmDelivery': 'Confirm Delivery',
    'orders.cancelOrder': 'Cancel Order',
    'orders.trackPackage': 'Track Package',
    'orders.from': 'From',
    'orders.to': 'To',
    
    // Messages
    'messages.title': 'Messages',
    'messages.newMessage': 'New Message',
    'messages.typeMessage': 'Type a message...',
    'messages.send': 'Send',
    'messages.noMessages': 'No messages yet',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.checkout': 'Checkout',
    'cart.total': 'Total',
    'cart.remove': 'Remove',
    'cart.continueShopping': 'Continue Shopping',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.shipping': 'Shipping Address',
    'checkout.payment': 'Payment Method',
    'checkout.card': 'Card Payment',
    'checkout.cod': 'Cash on Delivery',
    'checkout.placeOrder': 'Place Order',
    'checkout.processing': 'Processing...',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.viewAll': 'View All',
    'common.currency': 'RON',
    'common.price': 'Price',
    'common.noResults': 'No results found',
    'common.tryAgain': 'Try again',
    
    // Footer
    'footer.about': 'About Us',
    'footer.help': 'Help Center',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    'footer.copyright': 'All rights reserved.',
    
    // Admin
    'admin.dashboard': 'Dashboard Overview',
    'admin.welcome': 'Welcome to the admin panel. Monitor and manage your marketplace.',
    'admin.totalUsers': 'Total Users',
    'admin.registeredAccounts': 'Registered accounts',
    'admin.activeSellers': 'Active Sellers',
    'admin.withSubscription': 'With active subscription',
    'admin.activeListings': 'Active Listings',
    'admin.totalOrders': 'Total Orders',
    'admin.allTime': 'All time',
    'admin.platformRevenue': 'Platform Revenue',
    'admin.revenueDesc': 'Total revenue from completed orders',
    'admin.feeStructure': 'Current Fee Structure',
    'admin.activeFees': 'Active platform fees',
    'admin.buyerFee': 'Buyer Fee',
    'admin.sellerCommission': 'Seller Commission',
    'admin.sellerSubscription': 'Seller Monthly Fee',
    'admin.recentOrders': 'Recent Orders',
    'admin.latestTransactions': 'Latest transactions on the platform',
    'admin.noOrders': 'No orders yet',
  },
  ro: {
    // Header
    'header.search': 'Caută produse...',
    'header.sell': 'Vinde',
    'header.login': 'Autentificare',
    'header.signup': 'Înregistrare',
    'header.dashboard': 'Tabloul Meu',
    'header.listings': 'Anunțurile Mele',
    'header.favorites': 'Favorite',
    'header.messages': 'Mesaje',
    'header.orders': 'Comenzile Mele',
    'header.settings': 'Setări',
    'header.signout': 'Deconectare',
    'header.sellItem': 'Vinde un Articol',
    
    // Search
    'search.title': 'Caută Produse',
    'search.placeholder': 'Ce cauți?',
    'search.or': 'sau caută după imagine',
    'search.imageSearchDesc': 'Fă o poză sau încarcă o imagine pentru a găsi produse similare',
    'search.takePhoto': 'Fă Poză',
    'search.uploadImage': 'Încarcă Imagine',
    'search.searchByImage': 'Caută după Imagine',
    'search.analyzing': 'Analizez...',
    'search.analyzingImage': 'Analizez imaginea...',
    'search.invalidImage': 'Selectează un fișier imagine valid',
    
    // Home
    'home.hero.tagline': 'Cumpără și Vinde Inteligent',
    'home.hero.subtitle': 'Alătură-te milioanelor de oameni care descoperă oferte extraordinare. De la electronice la modă, găsește ceea ce cauți.',
    'home.hero.searchPlaceholder': 'Ce cauți?',
    'home.hero.popular': 'Popular',
    'home.hero.furniture': 'Mobilă',
    'home.hero.title': 'Cumpără și Vinde Local',
    'home.hero.cta': 'Începe să Cauți',
    'home.categories': 'Categorii',
    'home.featured': 'Anunțuri Promovate',
    'home.viewAll': 'Vezi Tot',
    'home.howItWorks': 'Cum Funcționează',
    'home.step1.title': 'Listează Articolul',
    'home.step1.desc': 'Fă poze și creează anunțul în câteva minute',
    'home.step2.title': 'Conectează-te cu Cumpărători',
    'home.step2.desc': 'Discută direct cu cumpărătorii interesați',
    'home.step3.title': 'Primește Plata Securizat',
    'home.step3.desc': 'Primește plata prin platforma noastră securizată',
    
    // Browse
    'browse.search': 'Caută articole...',
    'browse.filters': 'Filtre',
    'browse.category': 'Categorie',
    'browse.allCategories': 'Toate Categoriile',
    'browse.priceRange': 'Interval Preț',
    'browse.condition': 'Stare',
    'browse.anyCondition': 'Orice Stare',
    'browse.clearFilters': 'Șterge Filtrele',
    'browse.sort': 'Sortează după',
    'browse.newest': 'Cele Mai Noi',
    'browse.priceLow': 'Preț: Mic la Mare',
    'browse.priceHigh': 'Preț: Mare la Mic',
    'browse.itemsFound': 'articole găsite',
    'browse.noListings': 'Nu s-au găsit anunțuri pentru criteriile tale',
    
    // Conditions
    'condition.new': 'Nou',
    'condition.like_new': 'Ca Nou',
    'condition.good': 'Bun',
    'condition.fair': 'Acceptabil',
    'condition.poor': 'Uzat',
    
    // Dashboard
    'dashboard.welcome': 'Bine ai venit!',
    'dashboard.seller': 'Vânzător',
    'dashboard.newListing': 'Anunț Nou',
    'dashboard.becomeSeller': 'Devino Vânzător',
    'dashboard.subscription': 'Comision Platformă',
    'dashboard.subscribed': 'Activ',
    'dashboard.subscribe': 'Comision 8% la fiecare vânzare',
    'dashboard.manageSubscription': 'Vezi Comisioane',
    'dashboard.subscribeNow': 'Începe să Vinzi Gratuit',
    'dashboard.sellerBenefits': 'Beneficii vânzător: Listează produse gratuit, comision 8% doar când vinzi. Fără taxe lunare!',
    'dashboard.activeListings': 'Anunțuri Active',
    'dashboard.totalViews': 'Total Vizualizări',
    'dashboard.totalEarned': 'Total Câștigat',
    'dashboard.myFavorites': 'Favoritele Mele',
    'dashboard.itemsSaved': 'Articolele salvate de tine',
    'dashboard.chatWithUsers': 'Discută cu cumpărători și vânzători',
    'dashboard.manageAccount': 'Gestionează contul tău',
    'dashboard.myListings': 'Anunțurile Mele',
    'dashboard.noListings': 'Niciun anunț încă',
    'dashboard.startSelling': 'Începe să vinzi creând primul tău anunț',
    'dashboard.subscribeToSell': 'Activează accesul lunar pentru a deveni vânzător și a crea anunțuri',
    'dashboard.createListing': 'Creează Anunț',
    'dashboard.loading': 'Se încarcă...',
    'dashboard.subscriptionActivated': 'Acces activat!',
    'dashboard.canCreateListings': 'Acum poți crea anunțuri.',
    'dashboard.subscriptionCanceled': 'Plata accesului anulată',
    'dashboard.canSubscribeAnytime': 'Poți activa oricând.',
    
    // Settings tabs
    'settings.title': 'Setări',
    'settings.profile': 'Profil',
    'settings.payments': 'Plăți',
    'settings.payouts': 'Încasări',
    'settings.shipping': 'Livrare',
    'settings.seller': 'Vânzător',
    'settings.notifications': 'Alerte',
    'settings.security': 'Securitate',
    
    // Profile settings
    'settings.profileInfo': 'Informații Profil',
    'settings.profileDesc': 'Actualizează informațiile personale vizibile pentru alți utilizatori',
    'settings.changeAvatar': 'Schimbă Avatar',
    'settings.displayName': 'Nume Afișat',
    'settings.username': 'Nume Utilizator',
    'settings.email': 'Email',
    'settings.emailCantChange': 'Email-ul nu poate fi schimbat',
    'settings.bio': 'Descriere',
    'settings.bioPlaceholder': 'Spune-le altora despre tine...',
    'settings.location': 'Locație',
    'settings.phone': 'Telefon',
    'settings.saveChanges': 'Salvează Modificările',
    'settings.saving': 'Se salvează...',
    
    // Auth
    'auth.login': 'Autentificare',
    'auth.signup': 'Înregistrare',
    'auth.email': 'Email',
    'auth.password': 'Parolă',
    'auth.confirmPassword': 'Confirmă Parola',
    'auth.forgotPassword': 'Ai uitat parola?',
    'auth.noAccount': 'Nu ai cont?',
    'auth.hasAccount': 'Ai deja cont?',
    'auth.loginButton': 'Autentifică-te',
    'auth.signupButton': 'Creează Cont',
    
    // Listing
    'listing.buyNow': 'Cumpără Acum',
    'listing.addToCart': 'Adaugă în Coș',
    'listing.contactSeller': 'Contactează Vânzătorul',
    'listing.description': 'Descriere',
    'listing.sellerInfo': 'Informații Vânzător',
    'listing.memberSince': 'Membru din',
    'listing.viewProfile': 'Vezi Profilul',
    'listing.report': 'Raportează Anunțul',
    'listing.share': 'Distribuie',
    'listing.placeBid': 'Plasează Licitație',
    'listing.currentBid': 'Licitație Curentă',
    'listing.startingBid': 'Preț de Pornire',
    'listing.auctionEnds': 'Licitația Se Termină',
    'listing.inStock': 'În Stoc',
    'listing.outOfStock': 'Stoc Epuizat',
    'listing.freeShipping': 'Livrare Gratuită',
    'listing.shipping': 'Livrare',
    'listing.location': 'Locație',
    'listing.condition': 'Stare',
    'listing.sold': 'Vândut',
    'listing.promoted': 'Promovat',
    
    // Orders
    'orders.myPurchases': 'Cumpărăturile Mele',
    'orders.myReturns': 'Returnările Mele',
    'orders.pending': 'În Așteptare',
    'orders.paid': 'Plătit',
    'orders.shipped': 'Expediat',
    'orders.delivered': 'Livrat',
    'orders.cancelled': 'Anulat',
    'orders.refunded': 'Rambursat',
    'orders.awb': 'Număr Urmărire',
    'orders.addTracking': 'Adaugă AWB',
    'orders.confirmDelivery': 'Confirmă Primirea',
    'orders.cancelOrder': 'Anulează Comanda',
    'orders.trackPackage': 'Urmărește Coletul',
    'orders.from': 'De la',
    'orders.to': 'Către',
    
    // Messages
    'messages.title': 'Mesaje',
    'messages.newMessage': 'Mesaj Nou',
    'messages.typeMessage': 'Scrie un mesaj...',
    'messages.send': 'Trimite',
    'messages.noMessages': 'Niciun mesaj încă',
    
    // Cart
    'cart.title': 'Coș de Cumpărături',
    'cart.empty': 'Coșul tău este gol',
    'cart.checkout': 'Finalizare Comandă',
    'cart.total': 'Total',
    'cart.remove': 'Șterge',
    'cart.continueShopping': 'Continuă Cumpărăturile',
    
    // Checkout
    'checkout.title': 'Finalizare Comandă',
    'checkout.shipping': 'Adresă de Livrare',
    'checkout.payment': 'Metodă de Plată',
    'checkout.card': 'Plată cu Card',
    'checkout.cod': 'Plata la Livrare',
    'checkout.placeOrder': 'Plasează Comanda',
    'checkout.processing': 'Se procesează...',
    
    // Common
    'common.loading': 'Se încarcă...',
    'common.error': 'Eroare',
    'common.success': 'Succes',
    'common.cancel': 'Anulează',
    'common.save': 'Salvează',
    'common.delete': 'Șterge',
    'common.edit': 'Editează',
    'common.back': 'Înapoi',
    'common.next': 'Următorul',
    'common.submit': 'Trimite',
    'common.search': 'Caută',
    'common.viewAll': 'Vezi Tot',
    'common.currency': 'RON',
    'common.price': 'Preț',
    'common.noResults': 'Nu s-au găsit rezultate',
    'common.tryAgain': 'Încearcă din nou',
    
    // Footer
    'footer.about': 'Despre Noi',
    'footer.help': 'Centru de Ajutor',
    'footer.privacy': 'Politica de Confidențialitate',
    'footer.terms': 'Termeni și Condiții',
    'footer.contact': 'Contactează-ne',
    'footer.copyright': 'Toate drepturile rezervate.',
    
    // Admin
    'admin.dashboard': 'Prezentare Generală',
    'admin.welcome': 'Bine ai venit în panoul de administrare. Monitorizează și gestionează marketplace-ul.',
    'admin.totalUsers': 'Total Utilizatori',
    'admin.registeredAccounts': 'Conturi înregistrate',
    'admin.activeSellers': 'Vânzători Activi',
    'admin.withSubscription': 'Cu abonament activ',
    'admin.activeListings': 'Anunțuri Active',
    'admin.totalOrders': 'Total Comenzi',
    'admin.allTime': 'Din totdeauna',
    'admin.platformRevenue': 'Venituri Platformă',
    'admin.revenueDesc': 'Venituri totale din comenzi finalizate',
    'admin.feeStructure': 'Structura Taxelor',
    'admin.activeFees': 'Taxe active pe platformă',
    'admin.buyerFee': 'Taxă Cumpărător',
    'admin.sellerCommission': 'Comision Vânzător',
    'admin.sellerSubscription': 'Abonament Lunar Vânzător',
    'admin.recentOrders': 'Comenzi Recente',
    'admin.latestTransactions': 'Ultimele tranzacții pe platformă',
    'admin.noOrders': 'Nicio comandă încă',
  },
  de: {
    // Header
    'header.search': 'Artikel suchen...',
    'header.sell': 'Verkaufen',
    'header.login': 'Anmelden',
    'header.signup': 'Registrieren',
    'header.dashboard': 'Mein Dashboard',
    'header.listings': 'Meine Anzeigen',
    'header.favorites': 'Favoriten',
    'header.messages': 'Nachrichten',
    'header.orders': 'Meine Bestellungen',
    'header.settings': 'Einstellungen',
    'header.signout': 'Abmelden',
    'header.sellItem': 'Artikel verkaufen',
    
    // Search
    'search.title': 'Produkte suchen',
    'search.placeholder': 'Was suchen Sie?',
    'search.or': 'oder nach Bild suchen',
    'search.imageSearchDesc': 'Foto machen oder Bild hochladen um ähnliche Produkte zu finden',
    'search.takePhoto': 'Foto machen',
    'search.uploadImage': 'Bild hochladen',
    'search.searchByImage': 'Nach Bild suchen',
    'search.analyzing': 'Analysiere...',
    'search.analyzingImage': 'Bild wird analysiert...',
    'search.invalidImage': 'Bitte wählen Sie eine gültige Bilddatei',
    
    // Home
    'home.hero.tagline': 'Smart Kaufen & Verkaufen',
    'home.hero.subtitle': 'Millionen entdecken tolle Angebote. Von Elektronik bis Mode - finden Sie was Sie suchen.',
    'home.hero.searchPlaceholder': 'Was suchen Sie?',
    'home.hero.popular': 'Beliebt',
    'home.hero.furniture': 'Möbel',
    'home.hero.title': 'Lokal Kaufen & Verkaufen',
    'home.hero.cta': 'Jetzt stöbern',
    'home.categories': 'Kategorien',
    'home.featured': 'Empfohlene Anzeigen',
    'home.viewAll': 'Alle anzeigen',
    'home.howItWorks': 'So funktioniert es',
    'home.step1.title': 'Artikel einstellen',
    'home.step1.desc': 'Fotos machen und Anzeige in Minuten erstellen',
    'home.step2.title': 'Mit Käufern verbinden',
    'home.step2.desc': 'Direkt mit interessierten Käufern chatten',
    'home.step3.title': 'Sicher bezahlt werden',
    'home.step3.desc': 'Zahlung über unsere sichere Plattform erhalten',
    
    // Browse
    'browse.search': 'Artikel suchen...',
    'browse.filters': 'Filter',
    'browse.category': 'Kategorie',
    'browse.allCategories': 'Alle Kategorien',
    'browse.priceRange': 'Preisspanne',
    'browse.condition': 'Zustand',
    'browse.anyCondition': 'Beliebiger Zustand',
    'browse.clearFilters': 'Filter löschen',
    'browse.sort': 'Sortieren nach',
    'browse.newest': 'Neueste zuerst',
    'browse.priceLow': 'Preis: Niedrig bis Hoch',
    'browse.priceHigh': 'Preis: Hoch bis Niedrig',
    'browse.itemsFound': 'Artikel gefunden',
    'browse.noListings': 'Keine passenden Anzeigen gefunden',
    
    // Conditions
    'condition.new': 'Neu',
    'condition.like_new': 'Wie Neu',
    'condition.good': 'Gut',
    'condition.fair': 'Akzeptabel',
    'condition.poor': 'Gebraucht',
    
    // Dashboard
    'dashboard.welcome': 'Willkommen!',
    'dashboard.seller': 'Verkäufer',
    'dashboard.newListing': 'Neue Anzeige',
    'dashboard.becomeSeller': 'Verkäufer werden',
    'dashboard.subscription': 'Plattformgebühr',
    'dashboard.subscribed': 'Aktiv',
    'dashboard.subscribe': '8% Provision pro Verkauf',
    'dashboard.manageSubscription': 'Gebühren anzeigen',
    'dashboard.subscribeNow': 'Kostenlos verkaufen',
    'dashboard.sellerBenefits': 'Vorteile: Kostenlos inserieren, 8% Provision nur bei Verkauf. Keine monatlichen Gebühren!',
    'dashboard.activeListings': 'Aktive Anzeigen',
    'dashboard.totalViews': 'Gesamtansichten',
    'dashboard.totalEarned': 'Gesamt verdient',
    'dashboard.myFavorites': 'Meine Favoriten',
    'dashboard.itemsSaved': 'Gespeicherte Artikel',
    'dashboard.chatWithUsers': 'Mit Käufern & Verkäufern chatten',
    'dashboard.manageAccount': 'Konto verwalten',
    'dashboard.myListings': 'Meine Anzeigen',
    'dashboard.noListings': 'Noch keine Anzeigen',
    'dashboard.startSelling': 'Erstellen Sie Ihre erste Anzeige',
    'dashboard.subscribeToSell': 'Monatlichen Zugang aktivieren um Verkäufer zu werden',
    'dashboard.createListing': 'Anzeige erstellen',
    'dashboard.loading': 'Laden...',
    'dashboard.subscriptionActivated': 'Zugang aktiviert!',
    'dashboard.canCreateListings': 'Sie können jetzt Anzeigen erstellen.',
    'dashboard.subscriptionCanceled': 'Zugangszahlung abgebrochen',
    'dashboard.canSubscribeAnytime': 'Sie können jederzeit aktivieren.',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.submit': 'Absenden',
    'common.search': 'Suchen',
    'common.viewAll': 'Alle anzeigen',
    'common.currency': 'RON',
    'common.price': 'Preis',
    'common.noResults': 'Keine Ergebnisse gefunden',
    'common.tryAgain': 'Erneut versuchen',
    
    // Footer
    'footer.about': 'Über uns',
    'footer.help': 'Hilfezentrum',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.contact': 'Kontakt',
    'footer.copyright': 'Alle Rechte vorbehalten.',

    // Settings
    'settings.title': 'Einstellungen',
    'settings.profile': 'Profil',
    'settings.payments': 'Zahlungen',
    'settings.payouts': 'Auszahlungen',
    'settings.shipping': 'Versand',
    'settings.seller': 'Verkäufer',
    'settings.notifications': 'Benachrichtigungen',
    'settings.security': 'Sicherheit',
    'settings.profileInfo': 'Profilinformationen',
    'settings.profileDesc': 'Aktualisieren Sie Ihre persönlichen Informationen',
    'settings.changeAvatar': 'Avatar ändern',
    'settings.displayName': 'Anzeigename',
    'settings.username': 'Benutzername',
    'settings.email': 'E-Mail',
    'settings.emailCantChange': 'E-Mail kann nicht geändert werden',
    'settings.bio': 'Biografie',
    'settings.bioPlaceholder': 'Erzählen Sie anderen über sich...',
    'settings.location': 'Standort',
    'settings.phone': 'Telefon',
    'settings.saveChanges': 'Änderungen speichern',
    'settings.saving': 'Speichern...',

    // Auth
    'auth.login': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'auth.loginButton': 'Anmelden',
    'auth.signupButton': 'Konto erstellen',

    // Listing
    'listing.buyNow': 'Jetzt kaufen',
    'listing.addToCart': 'In den Warenkorb',
    'listing.contactSeller': 'Verkäufer kontaktieren',
    'listing.description': 'Beschreibung',
    'listing.sellerInfo': 'Verkäufer-Info',
    'listing.memberSince': 'Mitglied seit',
    'listing.viewProfile': 'Profil anzeigen',
    'listing.report': 'Anzeige melden',
    'listing.share': 'Teilen',
    'listing.placeBid': 'Gebot abgeben',
    'listing.currentBid': 'Aktuelles Gebot',
    'listing.startingBid': 'Startgebot',
    'listing.auctionEnds': 'Auktion endet',
    'listing.inStock': 'Auf Lager',
    'listing.outOfStock': 'Nicht vorrätig',
    'listing.freeShipping': 'Kostenloser Versand',
    'listing.shipping': 'Versand',
    'listing.location': 'Standort',
    'listing.condition': 'Zustand',
    'listing.sold': 'Verkauft',
    'listing.promoted': 'Beworben',

    // Orders
    'orders.myPurchases': 'Meine Einkäufe',
    'orders.myReturns': 'Meine Rücksendungen',
    'orders.pending': 'Ausstehend',
    'orders.paid': 'Bezahlt',
    'orders.shipped': 'Versendet',
    'orders.delivered': 'Geliefert',
    'orders.cancelled': 'Storniert',
    'orders.refunded': 'Erstattet',
    'orders.awb': 'Sendungsverfolgung',
    'orders.addTracking': 'Tracking hinzufügen',
    'orders.confirmDelivery': 'Lieferung bestätigen',
    'orders.cancelOrder': 'Bestellung stornieren',
    'orders.trackPackage': 'Paket verfolgen',
    'orders.from': 'Von',
    'orders.to': 'An',

    // Messages
    'messages.title': 'Nachrichten',
    'messages.newMessage': 'Neue Nachricht',
    'messages.typeMessage': 'Nachricht eingeben...',
    'messages.send': 'Senden',
    'messages.noMessages': 'Noch keine Nachrichten',

    // Cart
    'cart.title': 'Warenkorb',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.checkout': 'Zur Kasse',
    'cart.total': 'Gesamt',
    'cart.remove': 'Entfernen',
    'cart.continueShopping': 'Weiter einkaufen',

    // Checkout
    'checkout.title': 'Kasse',
    'checkout.shipping': 'Lieferadresse',
    'checkout.payment': 'Zahlungsmethode',
    'checkout.card': 'Kartenzahlung',
    'checkout.cod': 'Nachnahme',
    'checkout.placeOrder': 'Bestellung aufgeben',
    'checkout.processing': 'Verarbeitung...',

    // Admin
    'admin.dashboard': 'Dashboard-Übersicht',
    'admin.welcome': 'Willkommen im Admin-Bereich. Überwachen und verwalten Sie Ihren Marktplatz.',
    'admin.totalUsers': 'Gesamtnutzer',
    'admin.registeredAccounts': 'Registrierte Konten',
    'admin.activeSellers': 'Aktive Verkäufer',
    'admin.withSubscription': 'Mit aktivem Abo',
    'admin.activeListings': 'Aktive Anzeigen',
    'admin.totalOrders': 'Gesamtbestellungen',
    'admin.allTime': 'Insgesamt',
    'admin.platformRevenue': 'Plattform-Einnahmen',
    'admin.revenueDesc': 'Gesamteinnahmen aus abgeschlossenen Bestellungen',
    'admin.feeStructure': 'Gebührenstruktur',
    'admin.activeFees': 'Aktive Plattformgebühren',
    'admin.buyerFee': 'Käufergebühr',
    'admin.sellerCommission': 'Verkäuferprovision',
    'admin.sellerSubscription': 'Monatliche Verkäufergebühr',
    'admin.recentOrders': 'Neueste Bestellungen',
    'admin.latestTransactions': 'Letzte Transaktionen auf der Plattform',
    'admin.noOrders': 'Noch keine Bestellungen',
  },
  es: {
    // Header
    'header.search': 'Buscar artículos...',
    'header.sell': 'Vender',
    'header.login': 'Iniciar Sesión',
    'header.signup': 'Registrarse',
    'header.dashboard': 'Mi Panel',
    'header.listings': 'Mis Anuncios',
    'header.favorites': 'Favoritos',
    'header.messages': 'Mensajes',
    'header.orders': 'Mis Pedidos',
    'header.settings': 'Configuración',
    'header.signout': 'Cerrar Sesión',
    'header.sellItem': 'Vender un artículo',
    
    // Search
    'search.title': 'Buscar Productos',
    'search.placeholder': '¿Qué estás buscando?',
    'search.or': 'o buscar por imagen',
    'search.imageSearchDesc': 'Toma una foto o sube una imagen para encontrar productos similares',
    'search.takePhoto': 'Tomar Foto',
    'search.uploadImage': 'Subir Imagen',
    'search.searchByImage': 'Buscar por Imagen',
    'search.analyzing': 'Analizando...',
    'search.analyzingImage': 'Analizando imagen...',
    'search.invalidImage': 'Por favor selecciona un archivo de imagen válido',
    
    // Home
    'home.hero.tagline': 'Compra y Vende Inteligente',
    'home.hero.subtitle': 'Únete a millones descubriendo ofertas increíbles. Desde electrónica hasta moda, encuentra lo que buscas.',
    'home.hero.searchPlaceholder': '¿Qué estás buscando?',
    'home.hero.popular': 'Popular',
    'home.hero.furniture': 'Muebles',
    'home.hero.title': 'Compra y Vende Localmente',
    'home.hero.cta': 'Empezar a Buscar',
    'home.categories': 'Categorías',
    'home.featured': 'Anuncios Destacados',
    'home.viewAll': 'Ver Todo',
    'home.howItWorks': 'Cómo Funciona',
    'home.step1.title': 'Publica tu Artículo',
    'home.step1.desc': 'Toma fotos y crea tu anuncio en minutos',
    'home.step2.title': 'Conecta con Compradores',
    'home.step2.desc': 'Chatea directamente con compradores interesados',
    'home.step3.title': 'Recibe el Pago Seguro',
    'home.step3.desc': 'Recibe el pago a través de nuestra plataforma segura',
    
    // Browse
    'browse.search': 'Buscar artículos...',
    'browse.filters': 'Filtros',
    'browse.category': 'Categoría',
    'browse.allCategories': 'Todas las Categorías',
    'browse.priceRange': 'Rango de Precio',
    'browse.condition': 'Condición',
    'browse.anyCondition': 'Cualquier Condición',
    'browse.clearFilters': 'Limpiar Filtros',
    'browse.sort': 'Ordenar por',
    'browse.newest': 'Más Recientes',
    'browse.priceLow': 'Precio: Menor a Mayor',
    'browse.priceHigh': 'Precio: Mayor a Menor',
    'browse.itemsFound': 'artículos encontrados',
    'browse.noListings': 'No se encontraron anuncios que coincidan',
    
    // Conditions
    'condition.new': 'Nuevo',
    'condition.like_new': 'Como Nuevo',
    'condition.good': 'Bueno',
    'condition.fair': 'Aceptable',
    'condition.poor': 'Usado',
    
    // Dashboard
    'dashboard.welcome': '¡Bienvenido!',
    'dashboard.seller': 'Vendedor',
    'dashboard.newListing': 'Nuevo Anuncio',
    'dashboard.becomeSeller': 'Convertirse en Vendedor',
    'dashboard.subscription': 'Comisión de Plataforma',
    'dashboard.subscribed': 'Activo',
    'dashboard.subscribe': '8% comisión por venta',
    'dashboard.manageSubscription': 'Ver Comisiones',
    'dashboard.subscribeNow': 'Vender Gratis',
    'dashboard.sellerBenefits': 'Beneficios: Publica gratis, 8% comisión solo cuando vendes. ¡Sin cuotas mensuales!',
    'dashboard.activeListings': 'Anuncios Activos',
    'dashboard.totalViews': 'Total de Vistas',
    'dashboard.totalEarned': 'Total Ganado',
    'dashboard.myFavorites': 'Mis Favoritos',
    'dashboard.itemsSaved': 'Artículos guardados',
    'dashboard.chatWithUsers': 'Chatea con compradores y vendedores',
    'dashboard.manageAccount': 'Gestionar tu cuenta',
    'dashboard.myListings': 'Mis Anuncios',
    'dashboard.noListings': 'Aún no hay anuncios',
    'dashboard.startSelling': 'Comienza a vender creando tu primer anuncio',
    'dashboard.subscribeToSell': 'Activa el acceso mensual para convertirte en vendedor',
    'dashboard.createListing': 'Crear Anuncio',
    'dashboard.loading': 'Cargando...',
    'dashboard.subscriptionActivated': '¡Acceso activado!',
    'dashboard.canCreateListings': 'Ahora puedes crear anuncios.',
    'dashboard.subscriptionCanceled': 'Pago de acceso cancelado',
    'dashboard.canSubscribeAnytime': 'Puedes activar en cualquier momento.',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.submit': 'Enviar',
    'common.search': 'Buscar',
    'common.viewAll': 'Ver Todo',
    'common.currency': 'RON',
    'common.price': 'Precio',
    'common.noResults': 'No se encontraron resultados',
    'common.tryAgain': 'Intentar de nuevo',
    
    // Footer
    'footer.about': 'Sobre Nosotros',
    'footer.help': 'Centro de Ayuda',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.contact': 'Contáctanos',
    'footer.copyright': 'Todos los derechos reservados.',

    // Settings
    'settings.title': 'Configuración',
    'settings.profile': 'Perfil',
    'settings.payments': 'Pagos',
    'settings.payouts': 'Cobros',
    'settings.shipping': 'Envío',
    'settings.seller': 'Vendedor',
    'settings.notifications': 'Notificaciones',
    'settings.security': 'Seguridad',
    'settings.profileInfo': 'Información del Perfil',
    'settings.profileDesc': 'Actualiza tu información personal visible para otros usuarios',
    'settings.changeAvatar': 'Cambiar Avatar',
    'settings.displayName': 'Nombre para Mostrar',
    'settings.username': 'Nombre de Usuario',
    'settings.email': 'Correo Electrónico',
    'settings.emailCantChange': 'El correo no se puede cambiar',
    'settings.bio': 'Biografía',
    'settings.bioPlaceholder': 'Cuéntales a otros sobre ti...',
    'settings.location': 'Ubicación',
    'settings.phone': 'Teléfono',
    'settings.saveChanges': 'Guardar Cambios',
    'settings.saving': 'Guardando...',

    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.forgotPassword': '¿Olvidaste la contraseña?',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.loginButton': 'Iniciar Sesión',
    'auth.signupButton': 'Crear Cuenta',

    // Listing
    'listing.buyNow': 'Comprar Ahora',
    'listing.addToCart': 'Añadir al Carrito',
    'listing.contactSeller': 'Contactar Vendedor',
    'listing.description': 'Descripción',
    'listing.sellerInfo': 'Información del Vendedor',
    'listing.memberSince': 'Miembro desde',
    'listing.viewProfile': 'Ver Perfil',
    'listing.report': 'Reportar Anuncio',
    'listing.share': 'Compartir',
    'listing.placeBid': 'Hacer Oferta',
    'listing.currentBid': 'Oferta Actual',
    'listing.startingBid': 'Oferta Inicial',
    'listing.auctionEnds': 'La Subasta Termina',
    'listing.inStock': 'En Stock',
    'listing.outOfStock': 'Agotado',
    'listing.freeShipping': 'Envío Gratis',
    'listing.shipping': 'Envío',
    'listing.location': 'Ubicación',
    'listing.condition': 'Condición',
    'listing.sold': 'Vendido',
    'listing.promoted': 'Promocionado',

    // Orders
    'orders.myPurchases': 'Mis Compras',
    'orders.myReturns': 'Mis Devoluciones',
    'orders.pending': 'Pendiente',
    'orders.paid': 'Pagado',
    'orders.shipped': 'Enviado',
    'orders.delivered': 'Entregado',
    'orders.cancelled': 'Cancelado',
    'orders.refunded': 'Reembolsado',
    'orders.awb': 'Número de Seguimiento',
    'orders.addTracking': 'Añadir Seguimiento',
    'orders.confirmDelivery': 'Confirmar Entrega',
    'orders.cancelOrder': 'Cancelar Pedido',
    'orders.trackPackage': 'Rastrear Paquete',
    'orders.from': 'De',
    'orders.to': 'Para',

    // Messages
    'messages.title': 'Mensajes',
    'messages.newMessage': 'Nuevo Mensaje',
    'messages.typeMessage': 'Escribe un mensaje...',
    'messages.send': 'Enviar',
    'messages.noMessages': 'Aún no hay mensajes',

    // Cart
    'cart.title': 'Carrito de Compras',
    'cart.empty': 'Tu carrito está vacío',
    'cart.checkout': 'Finalizar Compra',
    'cart.total': 'Total',
    'cart.remove': 'Eliminar',
    'cart.continueShopping': 'Seguir Comprando',

    // Checkout
    'checkout.title': 'Finalizar Compra',
    'checkout.shipping': 'Dirección de Envío',
    'checkout.payment': 'Método de Pago',
    'checkout.card': 'Pago con Tarjeta',
    'checkout.cod': 'Pago Contra Entrega',
    'checkout.placeOrder': 'Realizar Pedido',
    'checkout.processing': 'Procesando...',

    // Admin
    'admin.dashboard': 'Panel General',
    'admin.welcome': 'Bienvenido al panel de administración. Monitorea y gestiona tu marketplace.',
    'admin.totalUsers': 'Usuarios Totales',
    'admin.registeredAccounts': 'Cuentas registradas',
    'admin.activeSellers': 'Vendedores Activos',
    'admin.withSubscription': 'Con suscripción activa',
    'admin.activeListings': 'Anuncios Activos',
    'admin.totalOrders': 'Pedidos Totales',
    'admin.allTime': 'Todos los tiempos',
    'admin.platformRevenue': 'Ingresos de la Plataforma',
    'admin.revenueDesc': 'Ingresos totales de pedidos completados',
    'admin.feeStructure': 'Estructura de Tarifas',
    'admin.activeFees': 'Tarifas activas de la plataforma',
    'admin.buyerFee': 'Tarifa del Comprador',
    'admin.sellerCommission': 'Comisión del Vendedor',
    'admin.sellerSubscription': 'Cuota Mensual del Vendedor',
    'admin.recentOrders': 'Pedidos Recientes',
    'admin.latestTransactions': 'Últimas transacciones en la plataforma',
    'admin.noOrders': 'Aún no hay pedidos',
  },
  zh: {
    // Header
    'header.search': '搜索商品...',
    'header.sell': '出售',
    'header.login': '登录',
    'header.signup': '注册',
    'header.dashboard': '我的面板',
    'header.listings': '我的商品',
    'header.favorites': '收藏夹',
    'header.messages': '消息',
    'header.orders': '我的订单',
    'header.settings': '设置',
    'header.signout': '退出登录',
    'header.sellItem': '出售商品',
    
    // Search
    'search.title': '搜索产品',
    'search.placeholder': '你在找什么？',
    'search.or': '或按图片搜索',
    'search.imageSearchDesc': '拍照或上传图片以查找类似产品',
    'search.takePhoto': '拍照',
    'search.uploadImage': '上传图片',
    'search.searchByImage': '按图片搜索',
    'search.analyzing': '分析中...',
    'search.analyzingImage': '正在分析图片...',
    'search.invalidImage': '请选择有效的图片文件',
    
    // Home
    'home.hero.tagline': '智能买卖',
    'home.hero.subtitle': '加入数百万人发现独特商品的超值优惠。从电子产品到时尚，找到你想要的。',
    'home.hero.searchPlaceholder': '你在找什么？',
    'home.hero.popular': '热门',
    'home.hero.furniture': '家具',
    'home.hero.title': '本地买卖',
    'home.hero.cta': '开始浏览',
    'home.categories': '分类',
    'home.featured': '精选商品',
    'home.viewAll': '查看全部',
    'home.howItWorks': '如何运作',
    'home.step1.title': '发布商品',
    'home.step1.desc': '拍照并在几分钟内创建您的商品列表',
    'home.step2.title': '与买家联系',
    'home.step2.desc': '直接与感兴趣的买家聊天',
    'home.step3.title': '安全收款',
    'home.step3.desc': '通过我们的安全平台收款',
    
    // Browse
    'browse.search': '搜索商品...',
    'browse.filters': '筛选',
    'browse.category': '分类',
    'browse.allCategories': '所有分类',
    'browse.priceRange': '价格范围',
    'browse.condition': '状况',
    'browse.anyCondition': '任何状况',
    'browse.clearFilters': '清除筛选',
    'browse.sort': '排序',
    'browse.newest': '最新优先',
    'browse.priceLow': '价格：从低到高',
    'browse.priceHigh': '价格：从高到低',
    'browse.itemsFound': '件商品',
    'browse.noListings': '未找到匹配的商品',
    
    // Conditions
    'condition.new': '全新',
    'condition.like_new': '几乎全新',
    'condition.good': '良好',
    'condition.fair': '一般',
    'condition.poor': '较差',
    
    // Dashboard
    'dashboard.welcome': '欢迎！',
    'dashboard.seller': '卖家',
    'dashboard.newListing': '新商品',
    'dashboard.becomeSeller': '成为卖家',
    'dashboard.subscription': '平台费用',
    'dashboard.subscribed': '已激活',
    'dashboard.subscribe': '每笔销售8%佣金',
    'dashboard.manageSubscription': '查看费用',
    'dashboard.subscribeNow': '免费开始销售',
    'dashboard.sellerBenefits': '卖家福利：免费发布商品，仅在销售时收取8%佣金。无月费！',
    'dashboard.activeListings': '在售商品',
    'dashboard.totalViews': '总浏览量',
    'dashboard.totalEarned': '总收入',
    'dashboard.myFavorites': '我的收藏',
    'dashboard.itemsSaved': '已保存的商品',
    'dashboard.chatWithUsers': '与买家和卖家聊天',
    'dashboard.manageAccount': '管理您的账户',
    'dashboard.myListings': '我的商品',
    'dashboard.noListings': '暂无商品',
    'dashboard.startSelling': '创建您的第一个商品开始销售',
    'dashboard.subscribeToSell': '激活月度访问权限成为卖家',
    'dashboard.createListing': '创建商品',
    'dashboard.loading': '加载中...',
    'dashboard.subscriptionActivated': '访问已激活！',
    'dashboard.canCreateListings': '您现在可以创建商品了。',
    'dashboard.subscriptionCanceled': '访问付款已取消',
    'dashboard.canSubscribeAnytime': '您可以随时激活。',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.back': '返回',
    'common.next': '下一步',
    'common.submit': '提交',
    'common.search': '搜索',
    'common.viewAll': '查看全部',
    'common.currency': 'RON',
    'common.price': '价格',
    'common.noResults': '未找到结果',
    'common.tryAgain': '重试',
    
    // Footer
    'footer.about': '关于我们',
    'footer.help': '帮助中心',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.contact': '联系我们',
    'footer.copyright': '版权所有。',

    // Settings
    'settings.title': '设置',
    'settings.profile': '个人资料',
    'settings.payments': '付款',
    'settings.payouts': '收款',
    'settings.shipping': '配送',
    'settings.seller': '卖家',
    'settings.notifications': '通知',
    'settings.security': '安全',
    'settings.profileInfo': '个人资料信息',
    'settings.profileDesc': '更新对其他用户可见的个人信息',
    'settings.changeAvatar': '更换头像',
    'settings.displayName': '显示名称',
    'settings.username': '用户名',
    'settings.email': '电子邮件',
    'settings.emailCantChange': '电子邮件无法更改',
    'settings.bio': '个人简介',
    'settings.bioPlaceholder': '向他人介绍自己...',
    'settings.location': '位置',
    'settings.phone': '电话',
    'settings.saveChanges': '保存更改',
    'settings.saving': '保存中...',

    // Auth
    'auth.login': '登录',
    'auth.signup': '注册',
    'auth.email': '电子邮件',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.forgotPassword': '忘记密码？',
    'auth.noAccount': '没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.loginButton': '登录',
    'auth.signupButton': '创建账户',

    // Listing
    'listing.buyNow': '立即购买',
    'listing.addToCart': '加入购物车',
    'listing.contactSeller': '联系卖家',
    'listing.description': '描述',
    'listing.sellerInfo': '卖家信息',
    'listing.memberSince': '加入时间',
    'listing.viewProfile': '查看资料',
    'listing.report': '举报商品',
    'listing.share': '分享',
    'listing.placeBid': '出价',
    'listing.currentBid': '当前出价',
    'listing.startingBid': '起拍价',
    'listing.auctionEnds': '拍卖结束',
    'listing.inStock': '有货',
    'listing.outOfStock': '缺货',
    'listing.freeShipping': '免运费',
    'listing.shipping': '运费',
    'listing.location': '位置',
    'listing.condition': '状况',
    'listing.sold': '已售',
    'listing.promoted': '推广',

    // Orders
    'orders.myPurchases': '我的购买',
    'orders.myReturns': '我的退货',
    'orders.pending': '待处理',
    'orders.paid': '已付款',
    'orders.shipped': '已发货',
    'orders.delivered': '已送达',
    'orders.cancelled': '已取消',
    'orders.refunded': '已退款',
    'orders.awb': '快递单号',
    'orders.addTracking': '添加追踪',
    'orders.confirmDelivery': '确认收货',
    'orders.cancelOrder': '取消订单',
    'orders.trackPackage': '追踪包裹',
    'orders.from': '从',
    'orders.to': '到',

    // Messages
    'messages.title': '消息',
    'messages.newMessage': '新消息',
    'messages.typeMessage': '输入消息...',
    'messages.send': '发送',
    'messages.noMessages': '暂无消息',

    // Cart
    'cart.title': '购物车',
    'cart.empty': '您的购物车是空的',
    'cart.checkout': '结算',
    'cart.total': '合计',
    'cart.remove': '移除',
    'cart.continueShopping': '继续购物',

    // Checkout
    'checkout.title': '结算',
    'checkout.shipping': '配送地址',
    'checkout.payment': '付款方式',
    'checkout.card': '银行卡支付',
    'checkout.cod': '货到付款',
    'checkout.placeOrder': '提交订单',
    'checkout.processing': '处理中...',

    // Admin
    'admin.dashboard': '仪表板概览',
    'admin.welcome': '欢迎来到管理面板。监控和管理您的市场。',
    'admin.totalUsers': '总用户数',
    'admin.registeredAccounts': '注册账户',
    'admin.activeSellers': '活跃卖家',
    'admin.withSubscription': '有活跃订阅',
    'admin.activeListings': '在售商品',
    'admin.totalOrders': '总订单',
    'admin.allTime': '所有时间',
    'admin.platformRevenue': '平台收入',
    'admin.revenueDesc': '已完成订单的总收入',
    'admin.feeStructure': '费用结构',
    'admin.activeFees': '活跃的平台费用',
    'admin.buyerFee': '买家费用',
    'admin.sellerCommission': '卖家佣金',
    'admin.sellerSubscription': '卖家月费',
    'admin.recentOrders': '最近订单',
    'admin.latestTransactions': '平台最新交易',
    'admin.noOrders': '暂无订单',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');
  const [detectedFromLocation, setDetectedFromLocation] = useState(false);

  // Auto-detect language based on IP geolocation
  useEffect(() => {
    const detectLanguage = async () => {
      // Check if user has manually set a language
      const savedLanguage = localStorage.getItem('preferred_language') as Language;
      if (savedLanguage && ['ro', 'en', 'de', 'es', 'zh'].includes(savedLanguage)) {
        setLanguageState(savedLanguage);
        return;
      }

      // Try timezone detection first (instant, no network)
      try {
        const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
        if (timezone === 'Europe/Bucharest') {
          setLanguageState('ro');
          setDetectedFromLocation(true);
          return;
        }
      } catch (e) {
        console.log('Timezone detection failed');
      }

      // Fallback: IP geolocation
      try {
        const response = await fetch('https://ipapi.co/json/', { 
          signal: AbortSignal.timeout(3000) 
        });
        if (response.ok) {
          const data = await response.json();
          // Only Romanian for Romania, English for everyone else
          if (data.country_code === 'RO') {
            setLanguageState('ro');
            setDetectedFromLocation(true);
          } else {
            setLanguageState('en');
            setDetectedFromLocation(true);
          }
        }
      } catch (e) {
        console.log('IP geolocation failed, using default English');
        setLanguageState('en');
      }
    };

    detectLanguage();
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferred_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, detectedFromLocation }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
